/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Subject = IDL.Record({
  'marks' : IDL.Nat,
  'name' : IDL.Text,
  'detailedNote' : IDL.Text,
});
export const AddSemesterRequest = IDL.Record({
  'id' : IDL.Text,
  'subjects' : IDL.Vec(Subject),
  'overallPerformance' : IDL.Text,
  'semesterNumber' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateStudentRequest = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'className' : IDL.Text,
  'psychologicalContext' : IDL.Text,
});
export const Time = IDL.Int;
export const StudentBase = IDL.Record({
  'id' : IDL.Text,
  'deleted' : IDL.Bool,
  'updatedTime' : IDL.Opt(Time),
  'name' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'createdTime' : Time,
  'className' : IDL.Text,
  'psychologicalContext' : IDL.Text,
});
export const SemesterData = IDL.Record({
  'subjects' : IDL.Vec(Subject),
  'overallPerformance' : IDL.Text,
  'semesterNumber' : IDL.Nat,
});
export const Student = IDL.Record({
  'base' : StudentBase,
  'semesters' : IDL.Vec(SemesterData),
});
export const UpdateSemesterRequest = IDL.Record({
  'id' : IDL.Text,
  'subjects' : IDL.Vec(Subject),
  'overallPerformance' : IDL.Text,
  'semesterNumber' : IDL.Nat,
});
export const UpdateStudentRequest = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'className' : IDL.Text,
  'psychologicalContext' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSemester' : IDL.Func([AddSemesterRequest], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'createStudent' : IDL.Func([CreateStudentRequest], [], []),
  'deleteSemester' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
  'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateSemester' : IDL.Func([UpdateSemesterRequest], [], []),
  'updateStudent' : IDL.Func([UpdateStudentRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Subject = IDL.Record({
    'marks' : IDL.Nat,
    'name' : IDL.Text,
    'detailedNote' : IDL.Text,
  });
  const AddSemesterRequest = IDL.Record({
    'id' : IDL.Text,
    'subjects' : IDL.Vec(Subject),
    'overallPerformance' : IDL.Text,
    'semesterNumber' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateStudentRequest = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'className' : IDL.Text,
    'psychologicalContext' : IDL.Text,
  });
  const Time = IDL.Int;
  const StudentBase = IDL.Record({
    'id' : IDL.Text,
    'deleted' : IDL.Bool,
    'updatedTime' : IDL.Opt(Time),
    'name' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'createdTime' : Time,
    'className' : IDL.Text,
    'psychologicalContext' : IDL.Text,
  });
  const SemesterData = IDL.Record({
    'subjects' : IDL.Vec(Subject),
    'overallPerformance' : IDL.Text,
    'semesterNumber' : IDL.Nat,
  });
  const Student = IDL.Record({
    'base' : StudentBase,
    'semesters' : IDL.Vec(SemesterData),
  });
  const UpdateSemesterRequest = IDL.Record({
    'id' : IDL.Text,
    'subjects' : IDL.Vec(Subject),
    'overallPerformance' : IDL.Text,
    'semesterNumber' : IDL.Nat,
  });
  const UpdateStudentRequest = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'className' : IDL.Text,
    'psychologicalContext' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSemester' : IDL.Func([AddSemesterRequest], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'createStudent' : IDL.Func([CreateStudentRequest], [], []),
    'deleteSemester' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
    'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateSemester' : IDL.Func([UpdateSemesterRequest], [], []),
    'updateStudent' : IDL.Func([UpdateStudentRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };