/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddSemesterRequest {
  'id' : string,
  'subjects' : Array<Subject>,
  'overallPerformance' : string,
  'semesterNumber' : bigint,
}
export interface CreateStudentRequest {
  'id' : string,
  'name' : string,
  'photoUrl' : [] | [string],
  'className' : string,
  'psychologicalContext' : string,
}
export interface SemesterData {
  'subjects' : Array<Subject>,
  'overallPerformance' : string,
  'semesterNumber' : bigint,
}
export interface Student {
  'base' : StudentBase,
  'semesters' : Array<SemesterData>,
}
export interface StudentBase {
  'id' : string,
  'deleted' : boolean,
  'updatedTime' : [] | [Time],
  'name' : string,
  'photoUrl' : [] | [string],
  'createdTime' : Time,
  'className' : string,
  'psychologicalContext' : string,
}
export interface Subject {
  'marks' : bigint,
  'name' : string,
  'detailedNote' : string,
}
export type Time = bigint;
export interface UpdateSemesterRequest {
  'id' : string,
  'subjects' : Array<Subject>,
  'overallPerformance' : string,
  'semesterNumber' : bigint,
}
export interface UpdateStudentRequest {
  'id' : string,
  'name' : string,
  'photoUrl' : [] | [string],
  'className' : string,
  'psychologicalContext' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSemester' : ActorMethod<[AddSemesterRequest], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'createStudent' : ActorMethod<[CreateStudentRequest], undefined>,
  'deleteSemester' : ActorMethod<[string, bigint], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStudent' : ActorMethod<[string], Student>,
  'isAdminAssigned' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateSemester' : ActorMethod<[UpdateSemesterRequest], undefined>,
  'updateStudent' : ActorMethod<[UpdateStudentRequest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];